modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="pixelmon_create_compat"
version="1.0.0"
displayName="Pixelmon Create Compat"
credits=""
displayURL=""
authors="Drai, Kadinu"


[[dependencies.pixelmon_create_compat]]
    modId="pixelmon"
    mandatory=false
    versionRange="[9.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelmon_create_compat]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.5_v0.3.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pixelmon_create_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


